### ISSUE TITLE
Backspace doesn't work

### ISSUE THREAD

**Issue by mwleeds** [flathub/org.vim.Vim#3]
Using vim from flathub, hitting Backspace while in Insert mode doesn't work. Using vim from the Endless apt repos, it does work.

**Comment by wjt** [comment]
I can't reproduce this on Endless OS 3.4.6 with org.vim.Vim 8.0.1433 and runtime/org.freedesktop.Platform/x86_64/1.6 commit 3b442ccf3e8eb746db8cca8779f37a8cf5038ff835f063ff8d53cdb330b94e4c. I'm using the built-in version of GNOME Terminal, locally.

Does backspace *never* work in insert mode, or does it work for characters inserted during the current insert mode "session"? I ask because Ye Olde Vi [only allowed the latter](https://stackoverflow.com/a/11560415). What does `:set backspace?` show for `org.vim.Vim` vs Endless's apt repo `vim`?

I have some memory that Vim in one of its Vi-compatible modes does not let you backspace past the beginning of the current `i` "session". So if you ha

**Comment by wjt** [comment]
If you can still reproduce this, please reopen with:

* Distro
* `:set backspace?` in the working & failing Vims
* Ideally a link to your config files!

**Comment by mwleeds** [comment]
I can still reproduce this.

- Distro: Endless 3.5.0 (dev)
- I don't understand what to do after typing `:set backspace?`
- See `.vim` and `.vimrc` in https://github.com/mwleeds/dotfiles

**Comment by wjt** [comment]
`:set backspace?<CR>` shows the current value of the `backspace` setting. What does it show in the working and non-working environments?

Which terminal are you using?

**Comment by mwleeds** [comment]
gnome-terminal

**Comment by mwleeds** [comment]
Interesting. Under the flatpak'd vim, it's `backspace=`. Under the vim from apt it's `backspace=indent,eol,start`.  And `set backspace=indent,eol,start` fixes the issue in the flatpak'd one.

**Comment by mwleeds** [comment]
Another Endless computer on 3.5.0 has backspace working in flatpak'd vim, so I suppose this is something specific to my `.vimrc`
